# Cardekho Car details Scraping

In [1]:
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

In [2]:
import requests

In [6]:
cars24=requests.get('https://www.cars24.com/buy-used-hyundai-cars-bengaluru/')
cars24

In [12]:
city=['bengaluru','chennai','new-delhi','mumbai','pune','hyderabad','kolkata','ahmedabad','jaipur','chandigarh']
brands=['hyundai','renault','mahindra','toyota','audi','honda','maruti','tata','ford','skoda']

capa = DesiredCapabilities.CHROME
capa["pageLoadStrategy"] = "eager" #since webpage has long loading time. This command will start scraping once 
driver = webdriver.Chrome(desired_capabilities=capa)  #the html is loaded.

location=[]
brand=[]
year=[]
model=[]
transmission=[]
kms=[]
variant=[]
owner=[]
fuel=[]
price=[]

for j in city:
    for l in brands:
        url='https://www.cars24.com/buy-used-{}-cars-{}/'.format(l,j)

        driver.get(url)
        
    #creating the instance to scroll down the page for data to load.
        SCROLL_PAUSE_TIME = 2
        CYCLES = 20

        html = driver.find_element_by_tag_name('html')
        html.send_keys(Keys.PAGE_DOWN)  
        html.send_keys(Keys.PAGE_DOWN)  
        time.sleep(SCROLL_PAUSE_TIME)

        for k in range(CYCLES):
            html.send_keys(Keys.PAGE_UP*5)
            html.send_keys(Keys.END)
            time.sleep(SCROLL_PAUSE_TIME)
          
        for k in driver.find_elements_by_xpath("//h2[@class='_3FpCg']"):
            year.append(k.text.split()[0])
                    
        for k in driver.find_elements_by_xpath("//h2[@class='_3FpCg']"):
            model.append(k.text[5:])
            
        for k in driver.find_elements_by_xpath("//p[@class='cvakB']/span"):
            transmission.append(k.text)
            
        for k in driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]"):
            kms.append(k.text.split()[0])
                               
        for k in driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]"):
            owner.append(k.text[:1])

        for k in driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]"):
            fuel.append(k.text)
        
        for k in driver.find_elements_by_xpath("//p[@class='cvakB']"):
            variant.append(k.text.replace(' Manual','').replace(' Automatic',''))

        for k in driver.find_elements_by_xpath("//div[@class='_7udZZ']/span"):
            price.append(k.text[1:])
            location.append(j)
            brand.append(l)
                
        print(len(fuel))
        
        df=pd.DataFrame({'Brands':brand,'Model':model,'Variant':variant,'Make Year':year,'Fuel':fuel,
                     'Transmission':transmission,'Driven Kilometers':kms,'Owners':owner,
                     'Location':location,'Price':price})
        
        df.to_csv('Carsdata.csv')

216
251
264
276
278
321
717
744
763
773
793
810
819
835
835
875
1187
1198
1215
1216
1762
1866
1967
2134
2150
2270
2870
2906
2997
3011
3451
3505
3553
3683
3687
3873
4753
4800
4820
4840
4860
4880
4900
4920
4924
4944
4964
4984
5004
5024
5044
5053
5055
5060
5060
5078
5259
5265
5271
5273
5293
5302
5305
5311
5312
5332
5352
5352
5358
5358
5378
5389
5393
5396
5397
5408
5428
5431
5433
5434
5454
5460
5464
5469
5469
5481
5674
5677
5684
5684
5704
5724
5744
5764
5778
5798
5818
5838
5858
5868

In [13]:
df

,Brands,Model,Variant,Make Year,Fuel,Transmission,Driven Kilometers,Owners,Location,Price
0,hyundai,Hyundai i10,SPORTZ 1.2 KAPPA2,2013,Petrol,Manual,"16,089",2,bengaluru,"3,90,099"
1,hyundai,Hyundai i10,SPORTZ 1.2 KAPPA2,2013,Petrol,Manual,"15,548",1,bengaluru,"4,19,299"
2,hyundai,Hyundai Santro Xing,GL PLUS,2011,Petrol,Manual,"10,252",1,bengaluru,"2,94,199"
3,hyundai,Hyundai Grand i10,ASTA 1.2 AT VTVT,2014,Petrol,Automatic,"21,727",1,bengaluru,"5,29,299"
4,hyundai,Hyundai i10,SPORTZ 1.2 KAPPA2,2012,Petrol,Manual,"43,142",1,bengaluru,"3,74,299"
...,...,...,...,...,...,...,...,...,...,...
5863,skoda,Skoda Yeti,AMBITION 2.0 TDI 4X2,2012,Diesel,Manual,"1,08,981",2,chandigarh,"3,66,499"
5864,skoda,Skoda Rapid,1.6 TDI MT AMBITION PLUS,2014,Diesel,Manual,"1,38,328",1,chandigarh,"3,61,999"
5865,skoda,Skoda Rapid,AMBITION 1.6 MPI MT PLUS,2014,Petrol,Manual,"1,34,412",1,chandigarh,"3,24,299"
5866,skoda,Skoda Rapid,1.5 TDI AT STYLE PLUS,2017,Diesel,Automatic,"1,37,938",1,chandigarh,"5,61,999"
5867,skoda,Skoda Rapid,1.5 TDI MT AMBITION,2017,Diesel,Manual,"1,62,200",1,chandigarh,"4,78,499"

In [6]:
#creating the excel file
df.to_excel('carsdekhodata.xlsx')

##### Completed